version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "develop" # should this be removed? changed? duplicated?
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "develop"
