---
version: 2
sphinx:
  configuration: docs/conf.py
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libgdal-dev
    - gdal-bin
python:
  install:
    - requirements: docs/rtd-requirements.txt
    - requirements: docs/requirements.txt
