---
name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish_pypi:
    if: github.repository == 'opendatacube/datacube-explorer'

    runs-on: ubuntu-latest
    # Permit authenticating to PyPI
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.10

      - name: Install Twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade \
           toml \
           wheel \
           twine
          python -m pip freeze

      - name: Build Package
        run: python setup.py sdist bdist_wheel

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
