---
name: Tests

on:
  pull_request:
    paths:
      - '**'

  push:
    branches:
      - develop
      - integrate_1.9
    paths:
      - '**'

env:
  IMAGE_NAME: opendatacube/explorer

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker
        run: |
          make build

      - name: Run tests
        run: |
          make up-d
          sleep 10
          make create-test-db-docker
          make test-docker
          make docker-clean

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
